name: Push to UAT

on:
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: push-to-uat
  cancel-in-progress: false

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dev branch
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: dev
          fetch-depth: 0
          token: ${{ github.token }}

      - name: Push dev to uat
        run: git push origin HEAD:uat
